import { launch, newPage, PHONE, DESKTOP, BASE, dismissTutorial, answerAll, screenOf } from "./harness.mjs";
const errors = []; const b = await launch();
const tag = process.argv[2] || "m";
const p = await newPage(b, tag, tag === "d" ? { viewport: { width: 1366, height: 768 } } : PHONE, errors);
await p.goto(BASE); await p.waitForTimeout(400); await dismissTutorial(p);
await p.fill("#player-one", "Avery"); await p.fill("#player-two", "Jordan");
await p.locator('#setup-form button[type="submit"]').click(); await p.waitForTimeout(300);
if (await p.locator("#sensitive-confirm").isVisible().catch(()=>false)) await p.click("#sensitive-confirm");
await p.screenshot({ path: `pp-${tag}-q1.png` });
const ow = await p.evaluate(() => [document.documentElement.scrollWidth, innerWidth]); console.log("overflow", ow);
console.log("p1", await answerAll(p, "A"));
await p.screenshot({ path: `pp-${tag}-lock.png` });
await p.click("#unlock-turn"); await p.waitForTimeout(300);
console.log("skip visible for p2:", await p.locator("#skip-question").count());
console.log("p2", await answerAll(p, "J"));
console.log("screen", await screenOf(p)); await p.screenshot({ path: `pp-${tag}-celebrate.png` });
await p.click("#open-reveal-board"); await p.waitForTimeout(600);
await p.screenshot({ path: `pp-${tag}-reveal.png`, fullPage: true });
const txt = await p.locator("body").innerText(); console.log("NaN present:", /NaN/.test(txt));
await p.click("#settings-button"); await p.waitForTimeout(400);
await p.screenshot({ path: `pp-${tag}-settings.png`, fullPage: true });
console.log("errors:", errors.length ? errors : "none");
await b.close();
